import { Journal, generateId, CATEGORY_COLORS } from './storage';

const now = Date.now();
const dayMs = 24 * 60 * 60 * 1000;

export const seedData: Journal[] = [
  {
    id: generateId(),
    title: "Morning Reflection",
    content: "Started the day with a clear mind. Went for a quick run and felt amazing. I need to make this a daily habit. The crisp air really helps me organize my thoughts before the day gets chaotic.",
    category: "Personal",
    mood: "Calm",
    tags: ["morning", "reflection", "running"],
    colorLabel: CATEGORY_COLORS["Personal"],
    isPinned: true,
    isFavorite: true,
    isArchived: false,
    isDeleted: false,
    createdAt: new Date(now - 2 * dayMs).toISOString(),
    updatedAt: new Date(now - 2 * dayMs).toISOString(),
  },
  {
    id: generateId(),
    title: "Project Milestone Reached",
    content: "Finally shipped the new dashboard! The team worked really hard on this. We celebrated with some pizza. I'm proud of what we accomplished despite the tight deadlines.",
    category: "Work",
    mood: "Excited",
    tags: ["milestone", "launch", "team"],
    colorLabel: CATEGORY_COLORS["Work"],
    isPinned: false,
    isFavorite: true,
    isArchived: false,
    isDeleted: false,
    createdAt: new Date(now - 5 * dayMs).toISOString(),
    updatedAt: new Date(now - 5 * dayMs).toISOString(),
  },
  {
    id: generateId(),
    title: "Learning Rust",
    content: "Started diving into Rust ownership model. It's confusing at first, but it starts making sense when you think about memory safety. I built a small CLI tool today.",
    category: "Study",
    mood: "Motivated",
    tags: ["rust", "programming", "learning"],
    colorLabel: CATEGORY_COLORS["Study"],
    isPinned: false,
    isFavorite: false,
    isArchived: false,
    isDeleted: false,
    createdAt: new Date(now - 8 * dayMs).toISOString(),
    updatedAt: new Date(now - 8 * dayMs).toISOString(),
  },
  {
    id: generateId(),
    title: "Japan Trip Ideas",
    content: "Places to visit in Kyoto:\n- Fushimi Inari Taisha\n- Arashiyama Bamboo Grove\n- Kinkaku-ji\n- Kiyomizu-dera\n\nNeed to look into rail passes and book hotels soon.",
    category: "Travel",
    mood: "Happy",
    tags: ["japan", "planning", "kyoto"],
    colorLabel: CATEGORY_COLORS["Travel"],
    isPinned: true,
    isFavorite: false,
    isArchived: false,
    isDeleted: false,
    createdAt: new Date(now - 12 * dayMs).toISOString(),
    updatedAt: new Date(now - 10 * dayMs).toISOString(),
  },
  {
    id: generateId(),
    title: "Overwhelmed with tasks",
    content: "Too many things on my plate right now. Need to prioritize and maybe delegate some work. I should talk to my manager about expectations for this quarter.",
    category: "Work",
    mood: "Stressed",
    tags: ["stress", "workload"],
    colorLabel: CATEGORY_COLORS["Work"],
    isPinned: false,
    isFavorite: false,
    isArchived: false,
    isDeleted: false,
    createdAt: new Date(now - 15 * dayMs).toISOString(),
    updatedAt: new Date(now - 15 * dayMs).toISOString(),
  },
  {
    id: generateId(),
    title: "New App Idea",
    content: "An app that helps you track your plant watering schedule. It could use AI to identify plants from photos and automatically suggest care routines.",
    category: "Ideas",
    mood: "Motivated",
    tags: ["startup", "plants", "ai"],
    colorLabel: CATEGORY_COLORS["Ideas"],
    isPinned: false,
    isFavorite: false,
    isArchived: false,
    isDeleted: false,
    createdAt: new Date(now - 1 * dayMs).toISOString(),
    updatedAt: new Date(now - 1 * dayMs).toISOString(),
  },
  {
    id: generateId(),
    title: "Marathon Training W1",
    content: "Completed week 1 of training. My legs are sore, but I feel good. Diet has been clean. Need to make sure I'm stretching properly.",
    category: "Health",
    mood: "Happy",
    tags: ["fitness", "marathon"],
    colorLabel: CATEGORY_COLORS["Health"],
    isPinned: false,
    isFavorite: true,
    isArchived: false,
    isDeleted: false,
    createdAt: new Date(now - 20 * dayMs).toISOString(),
    updatedAt: new Date(now - 20 * dayMs).toISOString(),
  },
  {
    id: generateId(),
    title: "Quarterly Goals",
    content: "1. Launch v2.0\n2. Run a half marathon\n3. Read 5 books\n4. Invest in learning a new language",
    category: "Goals",
    mood: "Neutral",
    tags: ["planning", "q3"],
    colorLabel: CATEGORY_COLORS["Goals"],
    isPinned: true,
    isFavorite: false,
    isArchived: false,
    isDeleted: false,
    createdAt: new Date(now - 30 * dayMs).toISOString(),
    updatedAt: new Date(now - 30 * dayMs).toISOString(),
  }
];
